# Generated by Django 3.2.6 on 2021-10-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://assets.servatom.com/notefy/avatars/dog.png', max_length=400, verbose_name='avatar'),
        ),
    ]
