# Generated by Django 3.2.6 on 2021-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shealth', '0002_auto_20210828_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
